development: &generic
  #min_prefix_len: 2
  mem_limit: 128M
  enable_star: 1
  #min_infix_len: 2
  min_prefix_len: 2
  #morphology: stem_ru
  charset_table: "0..9, a..z, _, @, A..Z->a..z, U+410..U+42F->U+430..U+44F, U+430..U+458"
  max_matches: 100000
  per_page: 100000
  mysql41: 9417

staging:
  <<: *generic
  mysql41: 9419

production:
  <<: *generic
  mysql41: 9417

test:
  <<: *generic
  mysql41: 9418
  quiet_deltas: true
